import type { Metadata } from "next";
import { TanstackProvider } from "@/providers/TanstackProvider";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/layout/Header/Header";
import { Footer } from "@/layout/Footer/Footer";
import "./layout.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>
          <h1 className="visually-hidden">Маруся - онлайн-кинотеатр</h1>
          <header className="header">
            <Header />
          </header>
          <main className="main">{children}</main>
          <footer className="footer">
            <Footer />
          </footer>
        </TanstackProvider>
      </body>
    </html>
  );
}
